name: Azure Policy CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'policy-module/**'
  pull_request:
    branches:
      - main
    paths:
      - 'policy-module/**'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_CLOUD_ORGANIZATION: succpinn-solutions-azure-policy

jobs:
  deploy-policy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.x
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./policy-module

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./policy-module

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      working-directory: ./policy-module
      continue-on-error: true

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false
      working-directory: ./policy-module

